### PR TITLE
Initial attemtp to fixup partial solves

### PR DESCRIPTION
**Pull request by mikeshardmind**
- This results in some amount of duplicated work, need to discuss in discord about a better long term idea

I haven't tested this yet, don't merge this prior to testing

### CODE REVIEW

**Comment by Tmktahu** [comment]
I think the math might be a bit cleaner and extensible if we leverage `calcItemContribution(...)` and do something like "current total stat minus the amount from items" for the `Stats` values. That way we don't need to move over all those hardcoded numbers over.

For the target stats block, I think it was correct? `targetXX.value` is the total number they want for the whole build, `currentCharacter.value.actionPoints` is the total amount currently on the sheet including items, and then `calcItemContribution(...)` is the amount from items. So the math should work out that the target stats contain specifically the amount of stats we want from only items.

**Comment by mikeshardmind** [comment]
> I think the math might be a bit cleaner and extensible if we leverage calcItemContribution(...) and do something like "current total stat minus the amount from items" for the Stats values—that way we don't need to move over all those hardcoded numbers over.

Possibly. The long-term on this is probably a new versioned entry point that takes in the entire current build state. In the context of that, the internals of the solver are currently structured to take what is essentially a partial build consisting of allocated stats, passive selection, items, runes, and sublimations, along with a *final* target for minimums. This would result in fewer transformations in total, only actually converting that information to raw numbers once in display and once in the solver, so my train of thought for this wasn't considering a long-term impact on having duplicated hard-coded constants in favor of simplicity on something that should be replaced later.

For context on passing in the entire current build state, passing this in along with minimum stats, *and what to solve for* will allow this to be fully composable long term, and the goal is to allow various things like a floating major point to be assignable by the solver as well as to be able to compare the performance of different builds

I can increase the priority on the solver handling a full build state over strictly performance improvements if you're concerned about how this exists currently with some amount of duplicated work.

> For the target stats block, I think it was correct? targetXX.value is the total number they want for the whole build, currentCharacter.value.XX is the total amount currently on the sheet including items, and then calcItemContribution(...) is the amount from items. So the math should work out that the target stats contain specifically the amount of stats we want from only items.

This should be the final set-wide minimums here, not just from gear. it happens to work for the dedicated auto-builder page without further changes there because it's seeing no allocated stats and just working to the best of it's ability in that context.

**Comment by Tmktahu** [comment]
Got it. I'll probably end up closing this PR and I'll spin up another one that moves the math logic out of the worker file and into a dedicated 'prepare params' function in useAutoBuilder so I can keep the worker clean of math.

But I'll leave this open for now so I can use it as a reference and copy-paste some stuff over.

**Comment by mikeshardmind** [comment]
I'm gonna close this. 

1. Partial solves are working well enough for now
2. Following up on the build codes being both stable and portable to python, this will be a more powerful tool to accurately ensure we are passing and expecting the same data with a clearly defined format and future entrypoints on the solver side will use it. + a basic configuration class to control solver goals.

**Pull request closed without merging**
